name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.10"
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.10-slim
            python_version: "3.10"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.9-alpine3.14
            python_version: "3.9"
          - name: python3.8-alpine3.10
            python_version: "3.8"
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Dependencies
        run: python3.9 -m pip install docker pytest
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
